//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Conseiller
	{

		public int fiabilité = 1;
		public int education = 1;
		public int inventivité = 1;

		public Conseiller ()
		{


		}
	}
}

