//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class Evenement
	{
		public string nom;
		public string description;
		public bool important;
		public bool choix;
		public string choix1;
		public string choix2;
		public string choix3;
		public List<ConditionTerrain> conditionT = new List<ConditionTerrain>();
		public List<ConditionRessource> conditionR = new List<ConditionRessource>();

		public Evenement ()
		{

		}
	}
}

