//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Evenement
	{
		public Evenement ()
		{
			string nom;
			string description;
			bool important;
			bool choix;
			string choix1;
			string choix2;
			string choix3;

		}
	}
}

